package cfdi

import (
	"encoding/xml"
	"strconv"

	"github.com/invopop/gobl.mx.cfdi/addon"
	"github.com/invopop/gobl.mx.cfdi/internal/format"
	"github.com/invopop/gobl/bill"
	"github.com/invopop/gobl/cal"
	"github.com/invopop/gobl/currency"
	"github.com/invopop/gobl/num"
	"github.com/invopop/gobl/org"
	"github.com/invopop/gobl/tax"
)

// Fixed values for CFDI type "P" documents as per SAT fill-in guide
const (
	PagoMoneda        = "XXX"       // Moneda (no currency)
	PagoClaveProdServ = "84111506"  // ClaveProdServ (payment services)
	PagoCantidad      = "1"         // Cantidad (one unit)
	PagoClaveUnidad   = "ACT"       // ClaveUnidad (activity)
	PagoDescripcion   = "Pago"      // Descripcion (payment)
	PagoObjetoImp     = ObjetoImpNo // ObjetoImp (not subject to tax)
)

var (
	PagoCantidadCero = num.AmountZero // SubTotal, Total, ValorUnitario and Importe (zero amount)
)

// Pagos schema constants
const (
	PagosVersion        = "2.0"
	PagosNamespace      = "http://www.sat.gob.mx/Pagos20"
	PagosSchemaLocation = "http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos20.xsd"
)

// Pagos stores the data of the payment receipts complement ("Complemento para recepción
// de pagos" 2.0) added to CFDI documents of type "P".
type Pagos struct {
	XMLName xml.Name `xml:"pago20:Pagos"`

	// Version is the version of the payment complement. Fixed to "2.0".
	Version string `xml:",attr"`

	// Totales reports the total amount of the payments and their taxes, expressed in
	// MXN.
	Totales *PagosTotales `xml:"pago20:Totales"`
	// Pago lists the payments received.
	Pago []*Pago `xml:"pago20:Pago"`
}

// PagosTotales stores the total amounts of the payments and the taxes that derive from
// them, expressed in MXN.
type PagosTotales struct {
	// TotalRetencionesIVA is the total of the IVA taxes withheld in the payments.
	TotalRetencionesIVA string `xml:",attr,omitempty"`
	// TotalRetencionesISR is the total of the ISR taxes withheld in the payments.
	TotalRetencionesISR string `xml:",attr,omitempty"`
	// TotalRetencionesIEPS is the total of the IEPS taxes withheld in the payments.
	TotalRetencionesIEPS string `xml:",attr,omitempty"`
	// TotalTrasladosBaseIVA16 is the total base of the IVA transferred at the 16% rate.
	TotalTrasladosBaseIVA16 string `xml:",attr,omitempty"`
	// TotalTrasladosImpuestoIVA16 is the total of the IVA taxes transferred at the 16% rate.
	TotalTrasladosImpuestoIVA16 string `xml:",attr,omitempty"`
	// TotalTrasladosBaseIVA8 is the total base of the IVA transferred at the 8% rate.
	TotalTrasladosBaseIVA8 string `xml:",attr,omitempty"`
	// TotalTrasladosImpuestoIVA8 is the total of the IVA taxes transferred at the 8% rate.
	TotalTrasladosImpuestoIVA8 string `xml:",attr,omitempty"`
	// TotalTrasladosBaseIVA0 is the total base of the IVA transferred at the 0% rate.
	TotalTrasladosBaseIVA0 string `xml:",attr,omitempty"`
	// TotalTrasladosImpuestoIVA0 is the total of the IVA taxes transferred at the 0% rate.
	TotalTrasladosImpuestoIVA0 string `xml:",attr,omitempty"`
	// TotalTrasladosBaseIVAExento is the total base of the IVA transferred exempt.
	TotalTrasladosBaseIVAExento string `xml:",attr,omitempty"`
	// MontoTotalPagos is the total of the payments reported in the Pago nodes.
	MontoTotalPagos string `xml:",attr"`
}

// Pago stores the data of a single payment received.
type Pago struct {
	// FechaPago is the date and time when the beneficiary receives the payment
	// (aaaa-mm-ddThh:mm:ss, ISO 8601; 12:00:00 when the time is unknown).
	FechaPago string `xml:",attr"`
	// FormaDePagoP is the key of the means by which the payment is made (c_FormaPago).
	FormaDePagoP string `xml:",attr"`
	// MonedaP is the key of the currency used to make the payment (ISO 4217).
	MonedaP string `xml:",attr"`
	// TipoCambioP is the exchange rate to MXN at the date of the payment. Required
	// when MonedaP is different from MXN.
	TipoCambioP string `xml:",attr,omitempty"`
	// Monto is the amount of the payment.
	Monto string `xml:",attr"`
	// NumOperacion is the cheque, authorisation, reference, SPEI tracking key or
	// analogous number that identifies the payment operation.
	NumOperacion string `xml:",attr,omitempty"`
	// RfcEmisorCtaOrd is the RFC of the entity issuing the ordering account.
	RfcEmisorCtaOrd string `xml:",attr,omitempty"`
	// NomBancoOrdExt is the name of the ordering bank, required when foreign.
	NomBancoOrdExt string `xml:",attr,omitempty"`
	// CtaOrdenante is the number of the account with which the payment was made.
	CtaOrdenante string `xml:",attr,omitempty"`
	// RfcEmisorCtaBen is the RFC of the entity operating the beneficiary account.
	RfcEmisorCtaBen string `xml:",attr,omitempty"`
	// CtaBeneficiario is the number of the account where the payment was received.
	CtaBeneficiario string `xml:",attr,omitempty"`
	// TipoCadPago is the key of the type of payment chain generated by the entity
	// receiving the payment (c_TipoCadenaPago).
	TipoCadPago string `xml:",attr,omitempty"`
	// CertPago is the certificate covering the payment, in base 64. Required when
	// TipoCadPago is set.
	CertPago string `xml:",attr,omitempty"`
	// CadPago is the original string of the payment receipt generated by the entity
	// issuing the beneficiary account. Required when TipoCadPago is set.
	CadPago string `xml:",attr,omitempty"`
	// SelloPago is the digital seal associated with the payment, in base 64. Required
	// when TipoCadPago is set.
	SelloPago string `xml:",attr,omitempty"`

	// DoctoRelacionado lists the documents related to the payment.
	DoctoRelacionado []*DoctoRelacionado `xml:"pago20:DoctoRelacionado"`
	// ImpuestosP summarises the taxes applicable to the amount of the payment
	// received, expressed in the payment currency.
	ImpuestosP *ImpuestosP `xml:"pago20:ImpuestosP,omitempty"`
}

// DoctoRelacionado stores the data of a document related to a payment.
type DoctoRelacionado struct {
	// IDDocumento is the identifier of the related document: the fiscal folio (UUID)
	// of an electronic invoice or the operation number of a digital document.
	IDDocumento string `xml:"IdDocumento,attr"`
	// Serie is the series of the related document, for internal control.
	Serie string `xml:",attr,omitempty"`
	// Folio is the folio of the related document, for internal control.
	Folio string `xml:",attr,omitempty"`
	// MonedaDR is the key of the currency of the amounts of the related document (ISO
	// 4217).
	MonedaDR string `xml:",attr"`
	// EquivalenciaDR is the number of units of the currency of the related document
	// that are equivalent to one unit of the payment currency. Required when the
	// currencies differ.
	EquivalenciaDR string `xml:",attr,omitempty"`
	// NumParcialidad is the number of the instalment that the payment corresponds to.
	NumParcialidad string `xml:",attr"`
	// ImpSaldoAnt is the outstanding balance of the previous instalment, or the total
	// amount of the related document for the first instalment.
	ImpSaldoAnt string `xml:",attr"`
	// ImpPagado is the amount paid for the related document.
	ImpPagado string `xml:",attr"`
	// ImpSaldoInsoluto is the difference between the previous balance and the amount
	// paid.
	ImpSaldoInsoluto string `xml:",attr"`
	// ObjetoImpDR expresses whether the payment of the related document is subject to
	// tax or not (c_ObjetoImp).
	ObjetoImpDR string `xml:",attr"`

	// ImpuestosDR reports the taxes applicable to the amount of the payment received,
	// expressed in the currency of the related document.
	ImpuestosDR *ImpuestosDR `xml:"pago20:ImpuestosDR,omitempty"`
}

// ImpuestosDR stores the taxes applicable to the amount paid for a related document.
type ImpuestosDR struct {
	// RetencionesDR lists the taxes withheld from the amount of the payment received.
	RetencionesDR *RetencionesDR `xml:"pago20:RetencionesDR,omitempty"`
	// TrasladosDR lists the taxes transferred on the amount of the payment received.
	TrasladosDR *TrasladosDR `xml:"pago20:TrasladosDR,omitempty"`
}

// RetencionesDR lists the taxes withheld from the amount paid for a related document.
type RetencionesDR struct {
	RetencionDR []*RetencionDR `xml:"pago20:RetencionDR"`
}

// TrasladosDR lists the taxes transferred on the amount paid for a related document.
type TrasladosDR struct {
	TrasladoDR []*TrasladoDR `xml:"pago20:TrasladoDR"`
}

// RetencionDR stores the data of a tax withheld from the amount paid for a related
// document.
type RetencionDR struct {
	// BaseDR is the base for the calculation of the withheld tax.
	BaseDR string `xml:",attr"`
	// ImpuestoDR is the key of the type of tax withheld (c_Impuesto).
	ImpuestoDR string `xml:",attr"`
	// TipoFactorDR is the key of the factor type applied to the base (c_TipoFactor).
	TipoFactorDR string `xml:",attr"`
	// TasaOCuotaDR is the rate or quota of the tax withheld.
	TasaOCuotaDR string `xml:",attr"`
	// ImporteDR is the amount of the tax withheld.
	ImporteDR string `xml:",attr"`
}

// TrasladoDR stores the data of a tax transferred on the amount paid for a related
// document.
type TrasladoDR struct {
	// BaseDR is the base for the calculation of the transferred tax.
	BaseDR string `xml:",attr"`
	// ImpuestoDR is the key of the type of tax transferred (c_Impuesto).
	ImpuestoDR string `xml:",attr"`
	// TipoFactorDR is the key of the factor type applied to the base (c_TipoFactor).
	TipoFactorDR string `xml:",attr"`
	// TasaOCuotaDR is the rate or quota of the tax transferred. Required when
	// TipoFactorDR is Tasa or Cuota.
	TasaOCuotaDR string `xml:",attr,omitempty"`
	// ImporteDR is the amount of the tax transferred. Required when
	// TipoFactorDR is Tasa or Cuota.
	ImporteDR string `xml:",attr,omitempty"`
}

// ImpuestosP stores the summary of the taxes applicable to the amount of a payment,
// expressed in the payment currency.
type ImpuestosP struct {
	// RetencionesP lists the taxes withheld from the amount of the payment. Required
	// when a related document registers a withheld tax.
	RetencionesP *RetencionesP `xml:"pago20:RetencionesP,omitempty"`
	// TrasladosP lists the taxes transferred on the amount of the payment. Required
	// when a related document registers a transferred tax.
	TrasladosP *TrasladosP `xml:"pago20:TrasladosP,omitempty"`
}

// RetencionesP lists the taxes withheld from the amount of a payment.
type RetencionesP struct {
	RetencionP []*RetencionP `xml:"pago20:RetencionP"`
}

// TrasladosP lists the taxes transferred on the amount of a payment.
type TrasladosP struct {
	TrasladoP []*TrasladoP `xml:"pago20:TrasladoP"`
}

// RetencionP stores the data of a tax withheld from the amount of a payment.
type RetencionP struct {
	// ImpuestoP is the key of the type of tax withheld (c_Impuesto).
	ImpuestoP string `xml:",attr"`
	// ImporteP is the amount of the tax withheld.
	ImporteP string `xml:",attr"`
}

// TrasladoP stores the data of a tax transferred on the amount of a payment.
type TrasladoP struct {
	// BaseP is the sum of the BaseDR attributes of the related documents for the
	// transferred tax.
	BaseP string `xml:",attr"`
	// ImpuestoP is the key of the type of tax transferred (c_Impuesto).
	ImpuestoP string `xml:",attr"`
	// TipoFactorP is the key of the factor type applied to the base (c_TipoFactor).
	TipoFactorP string `xml:",attr"`
	// TasaOCuotaP is the rate or quota of the tax transferred in the related
	// documents.
	TasaOCuotaP string `xml:",attr,omitempty"`
	// ImporteP is the sum of the transferred tax, grouped by ImpuestoP,
	// TipoFactorP and TasaOCuotaP.
	ImporteP string `xml:",attr,omitempty"`
}

// convertPayment converts a GOBL bill.Payment into a CFDI document of type "P" with the
// Pagos complement.
func convertPayment(pmt *bill.Payment) *Document {
	issuePlace := paymentIssuePlace(pmt)

	return &Document{
		CFDINamespace:  CFDINamespace,
		XSINamespace:   XSINamespace,
		PagosNamespace: PagosNamespace,
		SchemaLocation: format.SchemaLocation(CFDINamespace, CFDISchemaLocation) + " " + format.SchemaLocation(PagosNamespace, PagosSchemaLocation),
		Version:        CFDIVersion,

		TipoDeComprobante: pmt.Ext.Get(addon.ExtKeyDocType).String(),
		Serie:             pmt.Series.String(),
		Folio:             pmt.Code.String(),
		Fecha:             format.DateTime(pmt.IssueDate, pmt.IssueTime),
		LugarExpedicion:   issuePlace,

		// Fixed values for payment receipts as per SAT fill-in guide
		SubTotal:    PagoCantidadCero,
		Total:       PagoCantidadCero,
		Moneda:      PagoMoneda,
		Exportacion: ExportacionNoAplica,

		NoCertificado: FakeNoCertificado,

		CFDIRelacionados: newPaymentCfdiRelacionados(pmt),
		Emisor:           newEmisor(pmt.Supplier),
		Receptor:         newPaymentReceptor(pmt.Customer, issuePlace),
		Conceptos: &Conceptos{
			// Fixed concepto entry as per SAT fill-in guide for payment receipts
			Concepto: []*Concepto{
				{
					ClaveProdServ: PagoClaveProdServ,
					Cantidad:      PagoCantidad,
					ClaveUnidad:   PagoClaveUnidad,
					Desc:          PagoDescripcion,
					ValorUnitario: PagoCantidadCero,
					Importe:       PagoCantidadCero,
					ObjetoImp:     PagoObjetoImp,
				},
			},
		},
		ComplementoPagos: newPagos(pmt),
	}
}

func paymentIssuePlace(pmt *bill.Payment) string {
	if pmt.Ext.Has(addon.ExtKeyIssuePlace) {
		return pmt.Ext.Get(addon.ExtKeyIssuePlace).String()
	}
	// Fallback
	return pmt.Supplier.Ext.Get(addon.ExtKeyIssuePlace).String()
}

// newPaymentReceptor builds the receiver of a payment document.
func newPaymentReceptor(customer *org.Party, issuePlace string) *Receptor {
	receptor := newReceptor(customer, issuePlace)
	// The SAT requires the CFDI use of a payment receipt to always be "CP01" (Pagos),
	// for national, foreign and generic customers alike (see the SAT fill-in guide,
	// FAQ #6). Although the addon sets it on the GOBL customer, newReceptor only
	// reads that extension for Mexican customers and forces "S01" (no tax effects)
	// for foreign and generic ones, so it's overridden here to comply.
	receptor.UsoCFDI = addon.UsePayments.String()
	return receptor
}

func newPaymentCfdiRelacionados(pmt *bill.Payment) *CFDIRelacionados {
	if len(pmt.Preceding) == 0 {
		return nil
	}

	crs := &CFDIRelacionados{
		TipoRelacion: pmt.Preceding[0].Ext.Get(addon.ExtKeyRelType).String(),
	}

	for _, p := range pmt.Preceding {
		uuid := lookupUUID(p)
		if uuid != "" {
			cr := CFDIRelacionado{uuid}
			crs.CfdiRelacionado = append(crs.CfdiRelacionado, cr)
		}
	}

	return crs
}

func newPagos(pmt *bill.Payment) *Pagos {
	// Initialize the payment taxes accumulator
	taxes := new(paymentTaxes)

	tc := pagoTipoCambio(pmt)

	return &Pagos{
		Version: PagosVersion,
		Pago:    []*Pago{newPago(pmt, taxes, tc)},
		Totales: newPagosTotales(pmt, taxes, tc), // must be run after newPago to get the accumulated taxes
	}
}

func pagoTipoCambio(pmt *bill.Payment) num.Amount {
	if r := currency.MatchExchangeRate(pmt.ExchangeRates, pmt.Currency, currency.MXN); r != nil {
		return r.Amount
	}
	return num.MakeAmount(1, 0)
}

func newPago(pmt *bill.Payment, taxes *paymentTaxes, tc num.Amount) *Pago {
	// Exactly one method is guaranteed by addon rule PAYMENT-17
	method := pmt.Methods[0]

	return &Pago{
		FechaPago:        fechaPago(pmt),
		FormaDePagoP:     method.Ext.Get(addon.ExtKeyPaymentMeans).String(),
		MonedaP:          string(pmt.Currency),
		TipoCambioP:      tc.RescaleDown(6).String(),
		Monto:            pmt.Total.Rescale(pmt.Currency.Def().Subunits).String(),
		NumOperacion:     method.Ref,
		DoctoRelacionado: newDoctoRelacionados(pmt, taxes),
		ImpuestosP:       newImpuestosP(taxes), // Must be run after newDoctosRelacionados to get the accumulated taxes
	}
}

// fechaPago returns the date and time when the payment was received: the method's date,
// falling back to the payment's value date and then its issue date. GOBL doesn't store
// the time of a payment, so the SAT's default time for unknown times (12:00:00) is used.
func fechaPago(pmt *bill.Payment) string {
	d := pmt.IssueDate
	if m := pmt.Methods[0]; m.Date != nil {
		d = *m.Date
	} else if pmt.ValueDate != nil {
		d = *pmt.ValueDate
	}
	return d.WithTime(cal.MakeTime(12, 0, 0)).String()
}

// newDoctoRelacionados builds the list of related documents for a payment.
func newDoctoRelacionados(pmt *bill.Payment, taxes *paymentTaxes) []*DoctoRelacionado {
	var drs []*DoctoRelacionado
	for _, line := range pmt.Lines {
		if line == nil {
			continue
		}
		if dr := newDoctoRelacionado(line, pmt.Currency, taxes); dr != nil {
			drs = append(drs, dr)
		}
	}
	return drs
}

// newDoctoRelacionado builds the related document node from a payment line.
func newDoctoRelacionado(line *bill.PaymentLine, cur currency.Code, taxes *paymentTaxes) *DoctoRelacionado {
	if line.Document == nil {
		return nil
	}

	cu := cur.Def().Subunits

	dr := &DoctoRelacionado{
		IDDocumento:      lookupUUID(line.Document),
		Serie:            line.Document.Series.String(),
		Folio:            line.Document.Code.String(),
		NumParcialidad:   strconv.Itoa(line.Installment),
		ImpSaldoAnt:      saldoAnt(line).Rescale(cu).String(),
		ImpPagado:        line.Amount.Rescale(cu).String(),
		ImpSaldoInsoluto: saldoInsoluto(line).Rescale(cu).String(),
		ObjetoImpDR:      ObjetoImpNo, // Default for lines not carrying taxes

		// Addon rule PAYMENT-28 guarantees related documents share the payment
		// currency, so MonedaDR is that currency and EquivalenciaDR is always 1.
		// Supporting cross-currency documents would mean deriving their
		// document-currency amounts from the payment-currency values GOBL
		// exposes, which adds significant complexity and risks rounding drift.
		MonedaDR:       cur.String(),
		EquivalenciaDR: "1",
	}

	if i := newImpuestosDR(line.Tax, cu, taxes); i != nil {
		dr.ObjetoImpDR = ObjetoImpSi // The line does carry taxes, override the default
		dr.ImpuestosDR = i
	}

	return dr
}

// saldoAnt returns the outstanding balance of a payment line before this payment
func saldoAnt(line *bill.PaymentLine) num.Amount {
	if line.Payable == nil {
		// This should never happen as per the addon rule PAYMENT-22
		return num.Amount{}
	}
	// GOBL doesn't store the outstanding balance directly, so we derive it from the
	// payable and the advances amount.
	s := *line.Payable
	if line.Advances != nil {
		s = s.MatchPrecision(*line.Advances).Subtract(*line.Advances)
	}
	return s
}

// saldoInsoluto returns the outstanding balance of a payment line after this payment.
func saldoInsoluto(line *bill.PaymentLine) num.Amount {
	if line.Due == nil {
		// This should never happen as per the addon rule PAYMENT-23
		return num.Amount{}
	}
	return *line.Due
}

// newImpuestosDR builds the taxes of a document related to a payment from the line's tax
// total, accumulating them into the payment's taxes on the way.
func newImpuestosDR(total *tax.Total, cu uint32, taxes *paymentTaxes) *ImpuestosDR {
	if total == nil {
		return nil
	}

	var retenciones []*RetencionDR
	var traslados []*TrasladoDR

	for _, cat := range total.Categories {
		code, ok := taxCategoryMap[cat.Code]
		if !ok {
			continue
		}
		for _, rate := range cat.Rates {
			base := rate.Base.Rescale(cu)
			switch {
			case cat.Retained:
				if rate.Percent == nil {
					continue
				}
				importe := rate.Amount.Rescale(cu)
				retenciones = append(retenciones, &RetencionDR{
					BaseDR:       base.String(),
					ImpuestoDR:   code,
					TipoFactorDR: TipoFactorTasa,
					TasaOCuotaDR: format.TaxPercent(rate.Percent),
					ImporteDR:    importe.String(),
				})
				// accumulate the retained tax for summary and totals
				taxes.addRetention(code, importe)

			case rate.Percent == nil:
				// No percent means an exempt transfer, which a calculated
				// rate always reports with a zero amount.
				traslados = append(traslados, &TrasladoDR{
					BaseDR:       base.String(),
					ImpuestoDR:   code,
					TipoFactorDR: TipoFactorExento,
				})
				// accumulate the exempt transfer for summary and totals
				taxes.addTransfer(code, TipoFactorExento, "", base, num.MakeAmount(0, cu))

			default:
				importe := rate.Amount.Rescale(cu)
				tasa := format.TaxPercent(rate.Percent)
				traslados = append(traslados, &TrasladoDR{
					BaseDR:       base.String(),
					ImpuestoDR:   code,
					TipoFactorDR: TipoFactorTasa,
					TasaOCuotaDR: tasa,
					ImporteDR:    importe.String(),
				})
				// accumulate the transferred tax for summary and totals
				taxes.addTransfer(code, TipoFactorTasa, tasa, base, importe)
			}
		}
	}
	if len(retenciones) == 0 && len(traslados) == 0 {
		return nil
	}

	impuestos := new(ImpuestosDR)
	if len(retenciones) > 0 {
		impuestos.RetencionesDR = &RetencionesDR{retenciones}
	}
	if len(traslados) > 0 {
		impuestos.TrasladosDR = &TrasladosDR{traslados}
	}

	return impuestos
}

// newImpuestosP builds the tax summary of a payment from the accumulated taxes of its
// related documents.
func newImpuestosP(taxes *paymentTaxes) *ImpuestosP {
	if len(taxes.retentions) == 0 && len(taxes.transfers) == 0 {
		return nil
	}

	impuestos := new(ImpuestosP)
	if len(taxes.retentions) > 0 {
		retenciones := make([]*RetencionP, len(taxes.retentions))
		for i, r := range taxes.retentions {
			retenciones[i] = &RetencionP{
				ImpuestoP: r.code,
				ImporteP:  r.amount.String(),
			}
		}
		impuestos.RetencionesP = &RetencionesP{retenciones}
	}
	if len(taxes.transfers) > 0 {
		traslados := make([]*TrasladoP, len(taxes.transfers))
		for i, t := range taxes.transfers {
			tp := &TrasladoP{
				BaseP:       t.base.String(),
				ImpuestoP:   t.code,
				TipoFactorP: t.factor,
			}
			if t.factor != TipoFactorExento {
				tp.TasaOCuotaP = t.rate
				tp.ImporteP = t.amount.String()
			}
			traslados[i] = tp
		}
		impuestos.TrasladosP = &TrasladosP{traslados}
	}

	return impuestos
}

// newPagosTotales builds the totals of the Pagos complement from the accumulated taxes of
// the payment's related documents.
func newPagosTotales(pmt *bill.Payment, taxes *paymentTaxes, tc num.Amount) *PagosTotales {
	totales := new(PagosTotales)

	for _, r := range taxes.retentions {
		switch r.code {
		case satTaxVAT:
			totales.TotalRetencionesIVA = mxn(r.amount, tc)
		case satTaxISR:
			totales.TotalRetencionesISR = mxn(r.amount, tc)
		case satTaxIEPS:
			totales.TotalRetencionesIEPS = mxn(r.amount, tc)
		}
	}

	for _, t := range taxes.transfers {
		if t.code != satTaxVAT {
			continue
		}
		if t.factor == TipoFactorExento {
			totales.TotalTrasladosBaseIVAExento = mxn(t.base, tc)
			continue
		}
		switch t.rate {
		case vatRate16:
			totales.TotalTrasladosBaseIVA16 = mxn(t.base, tc)
			totales.TotalTrasladosImpuestoIVA16 = mxn(t.amount, tc)
		case vatRate8:
			totales.TotalTrasladosBaseIVA8 = mxn(t.base, tc)
			totales.TotalTrasladosImpuestoIVA8 = mxn(t.amount, tc)
		case vatRate0:
			totales.TotalTrasladosBaseIVA0 = mxn(t.base, tc)
			totales.TotalTrasladosImpuestoIVA0 = mxn(t.amount, tc)
		}
	}

	totales.MontoTotalPagos = mxn(pmt.Total, tc)

	return totales
}

// mxn converts an amount in the payment's currency into MXN using the given exchange rate
// as required by the SAT fill-in guide for the totals of the Pagos complement.
func mxn(a, tc num.Amount) string {
	return a.Upscale(4).Multiply(tc).Rescale(zero.Exp()).String()
}

// Auxiliary constants, types and values used to accumulate a payment's taxes while its
// related documents are converted, so the payment's tax summary (ImpuestosP) and the
// complement's totals (Totales) can be built from them.

// SAT VAT rates distinguished in the totals of the Pagos complement.
const (
	vatRate16 = "0.160000"
	vatRate8  = "0.080000"
	vatRate0  = "0.000000"
)

// paymentTax is a tax amount accumulated for a payment used by both transfers and
// retentions.
type paymentTax struct {
	code   string     // SAT tax type (c_Impuesto)
	factor string     // SAT factor type (c_TipoFactor); transfers only
	rate   string     // rate applied to the base (TasaOCuota); transfers only
	base   num.Amount // taxable base; transfers only
	amount num.Amount // tax amount
}

// paymentTaxes groups and accumulates the taxes of the documents related to a payment.
type paymentTaxes struct {
	retentions []*paymentTax
	transfers  []*paymentTax
}

func (pt *paymentTaxes) addRetention(code string, amount num.Amount) {
	for _, r := range pt.retentions {
		if r.code == code {
			r.amount = r.amount.MatchPrecision(amount).Add(amount)
			return
		}
	}
	pt.retentions = append(pt.retentions, &paymentTax{code: code, amount: amount})
}

func (pt *paymentTaxes) addTransfer(code, factor, rate string, base, amount num.Amount) {
	for _, t := range pt.transfers {
		if t.code == code && t.factor == factor && t.rate == rate {
			t.base = t.base.MatchPrecision(base).Add(base)
			t.amount = t.amount.MatchPrecision(amount).Add(amount)
			return
		}
	}
	pt.transfers = append(pt.transfers, &paymentTax{
		code:   code,
		factor: factor,
		rate:   rate,
		base:   base,
		amount: amount,
	})
}
