package cfdi

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/invopop/gobl"
	addon "github.com/invopop/gobl/addons/mx/cfdi"
	"github.com/invopop/gobl/head"
	"github.com/invopop/gobl/regimes/mx"
)

// TimbreFiscalDigital namespace and schema constants
const (
	TimbreNamespace      = "http://www.sat.gob.mx/TimbreFiscalDigital"
	TimbreSchemaLocation = "http://www.sat.gob.mx/sitio_internet/cfd/TimbreFiscalDigital/TimbreFiscalDigitalv11.xsd"
	TimbreVersion        = "1.1"

	satVerifyBaseURL = "https://verificacfdi.facturaelectronica.sat.gob.mx/default.aspx"
	// ?&id=7789e672-4d89-4b5b-8ed5-c85eb1ddca27&re=RBL2206107N8&rr=INS210623QU7&tt=000000000000022576.570000&fe=A9fALQ==
)

// TimbreFiscalDigital represents the digital fiscal stamp (Timbre Fiscal Digital)
// that validates a CFDI document.
type TimbreFiscalDigital struct {
	// Version is the version of the TimbreFiscalDigital standard (fixed at "1.1")
	Version string `xml:"Version,attr"`

	// UUID is the fiscal folio (36-character UUID) of the stamping transaction
	// conforming to RFC 4122 standard
	UUID string `xml:"UUID,attr"`

	// FechaTimbrado is the date and time when the stamp was generated by the SAT
	// certification. Format: YYYY-MM-DDThh:mm:ss in Mexico Central Time Zone
	FechaTimbrado string `xml:"FechaTimbrado,attr"`

	// RfcProvCertif is the RFC of the digital fiscal certificate provider
	// that generates the fiscal stamp
	RfcProvCertif string `xml:"RfcProvCertif,attr"`

	// Leyenda is an optional field to record information that the SAT
	// communicates to CFDI users (12-150 characters)
	Leyenda string `xml:"Leyenda,attr,omitempty"`

	// SelloCFD contains the digital seal of the CFDI that has been stamped,
	// expressed as a Base64 encoded string
	SelloCFD string `xml:"SelloCFD,attr"`

	// NoCertificadoSAT is the serial number of the SAT certificate used to
	// generate the digital seal of the fiscal stamp (20 digits)
	NoCertificadoSAT string `xml:"NoCertificadoSAT,attr"`

	// SelloSAT contains the digital seal of the fiscal stamp itself,
	// expressed as a Base64 encoded string
	SelloSAT string `xml:"SelloSAT,attr"`
}

// Stamp takes the provided structured stamp data and applies it to the envelope.
// This should be done after the CFDI document has been processed and signed
// by a PAC (Proveedor Autorizado de Certificación) in Mexico.
func Stamp(env *gobl.Envelope, doc *Document) error {
	t := doc.ComplementoTimbreFiscalDigital
	if t == nil {
		return nil
	}

	env.Head.AddStamp(&head.Stamp{
		Provider: mx.StampSATUUID,
		Value:    t.UUID,
	})
	env.Head.AddStamp(&head.Stamp{
		Provider: addon.StampSignature,
		Value:    t.SelloCFD,
	})
	env.Head.AddStamp(&head.Stamp{
		Provider: addon.StampSerial,
		Value:    doc.NoCertificado,
	})
	env.Head.AddStamp(&head.Stamp{
		Provider: mx.StampSATSignature,
		Value:    t.SelloSAT,
	})
	env.Head.AddStamp(&head.Stamp{
		Provider: mx.StampSATSerial,
		Value:    t.NoCertificadoSAT,
	})
	env.Head.AddStamp(&head.Stamp{
		Provider: mx.StampSATTimestamp,
		Value:    t.FechaTimbrado,
	})
	env.Head.AddStamp(&head.Stamp{
		Provider: mx.StampSATChain,
		Value:    buildChain(t),
	})
	// Provider RFC not required, but if its there, add it.
	if t.RfcProvCertif != "" {
		env.Head.AddStamp(&head.Stamp{
			Provider: mx.StampSATProviderRFC,
			Value:    t.RfcProvCertif,
		})
	}

	// Generate and add the QR code.
	qr, err := buildQRCode(doc)
	if err != nil {
		return fmt.Errorf("building QR code: %w", err)
	}
	env.Head.AddStamp(&head.Stamp{
		Provider: mx.StampSATURL,
		Value:    qr,
	})

	return nil
}

func buildQRCode(doc *Document) (string, error) {
	if doc == nil || doc.ComplementoTimbreFiscalDigital == nil || doc.Emisor == nil || doc.Receptor == nil || len(doc.Sello) < 8 {
		return "", fmt.Errorf("document is missing required fields")
	}
	base, err := url.Parse(satVerifyBaseURL)
	if err != nil {
		return "", fmt.Errorf("parsing base URL: %w", err)
	}
	// Manually build up the query so that we don't escape the `=` included
	// in the signature. When encoded, the SAT website does not read them
	// correctly :facepalm:.
	q := []string{
		fmt.Sprintf("id=%s", doc.ComplementoTimbreFiscalDigital.UUID),
		fmt.Sprintf("tt=%s", doc.Total),
		fmt.Sprintf("re=%s", doc.Emisor.Rfc),
		fmt.Sprintf("rr=%s", doc.Receptor.Rfc),
		fmt.Sprintf("fe=%s", doc.Sello[len(doc.Sello)-8:]),
	}
	base.RawQuery = strings.Join(q, "&")

	return base.String(), nil
}

// buildChain builds the chain string for the stamp according to
// https://www.sat.gob.mx/sitio_internet/cfd/TimbreFiscalDigital/cadenaoriginal_TFD_1_1.xslt
func buildChain(timbre *TimbreFiscalDigital) string {
	chain := "|"
	chain += "|" + normalizeSpace(timbre.Version)
	chain += "|" + normalizeSpace(timbre.UUID)
	chain += "|" + normalizeSpace(timbre.FechaTimbrado)
	chain += "|" + normalizeSpace(timbre.RfcProvCertif)
	if timbre.Leyenda != "" {
		chain += "|" + normalizeSpace(timbre.Leyenda)
	}
	chain += "|" + normalizeSpace(timbre.SelloCFD)
	chain += "|" + normalizeSpace(timbre.NoCertificadoSAT)
	chain += "||"
	return chain
}

// normalizeSpace replicates the behaviour of the normalize-space function in XSLT
func normalizeSpace(s string) string {
	return strings.Join(strings.Fields(s), " ")
}
